#include <msp430.h>
#include "msp430cp_device.h"
#include "msp430cp_registers.h"

// GPIO registers
REG_8b PxIN[GPIO_PORT_COUNT] = { &P1IN, &P2IN, &P3IN, &P4IN, &P5IN, &P6IN, &P7IN, &P8IN };
REG_8b PxOUT[GPIO_PORT_COUNT] = { &P1OUT, &P2OUT, &P3OUT, &P4OUT, &P5OUT, &P6OUT, &P7OUT, &P8OUT };
REG_8b PxDIR[GPIO_PORT_COUNT] = { &P1DIR, &P2DIR, &P3DIR, &P4DIR, &P5DIR, &P6DIR, &P7DIR, &P8DIR };
REG_8b PxREN[GPIO_PORT_COUNT] = { &P1REN, &P2REN, &P3REN, &P4REN, &P5REN, &P6REN, &P7REN, &P8REN };
REG_8b PxSEL[GPIO_PORT_COUNT] = { &P1SEL, &P2SEL, &P3SEL, &P4SEL, &P5SEL, &P6SEL, &P7SEL, &P8SEL };
#ifdef GPIO_PORT_HAS_FUNSEL2
REG_8b PxSEL2[GPIO_PORT_COUNT] = { &P1SEL2, &P2SEL2, &P3SEL2, &P4SEL2, &P5SEL2, &P6SEL2, &P7SEL2, &P8SEL2 };
#endif
#ifdef GPIO_PORT_HAS_DS
REG_8b PxDS[GPIO_PORT_COUNT] = { &P1DS, &P2DS, &P3DS, &P4DS, &P5DS, &P6DS, &P7DS, &P8DS };
#endif
REG_8b PxIE[GPIO_PORT_SUPPORT_INT_COUNT] = { &P1IE, &P2IE };
REG_8b PxIFG[GPIO_PORT_SUPPORT_INT_COUNT] = { &P1IFG, &P2IFG };
REG_8b PxIES[GPIO_PORT_SUPPORT_INT_COUNT] = { &P1IES, &P2IES };
